### ISSUE TITLE
Serve fails if there's no package.json

### ISSUE THREAD

**Issue by biilmann** [netlify/zip-it-and-ship-it#15]
If there's no package.json in either the function folder or the root, we fail to determine
the module path and break with a stacktrace.

**Comment by bcomnes** [comment]
If there is no package.json, we should stop looking up from the effective cwd (perhaps set as a root directory?).

**Comment by ehmicky** [comment]
The package root is used for four things:
  1) [determining the file paths](https://github.com/netlify/zip-it-and-ship-it/blob/42105cdc515a4c957ba8c210ed79e7240031acbc/src/zip.js#L89) inside the zip archive. However if #49 gets merged, the common ancestor will be used instead, i.e. no `package.json` should not be an issue anymore.
  2) excluding the non-required `node_modules` when targeting a functions directory. This has been fixed by 9c2b50a29239d07e7051e395f279863712dfb81f
  3) resolving [`require("moduleName")`](https://github.com/netlify/zip-it-and-ship-it/blob/42105cdc515a4c957ba8c210ed79e7240031acbc/src/finders.js#L56). Consequently dependencies searching is [disabled](https://github.com/netlify/zip-it-and-ship-it/blob/42105cdc515a4c957ba8c210ed79e7240031acbc/src/zip.js#L45) when no `package.json` is found. However I believe the file doing the `require()` statement should be used as the `resolve` base instead. This is implemented as part of #48.
  4) finding out the `optionalDependencies`. If no `package.json` is present, we default to none, so this should not be an issue.

I.e. this should be solved once #49 and #48 gets merged. I'm also adding tests in #47 to cover this case.
