### ISSUE TITLE
[TODO] run babel-register if .babelrc detected

### ISSUE THREAD

**Issue by sw-yx** [netlify/zip-it-and-ship-it#21]
these are implementation notes for a possible babel standalone feature in ZISI.

- deps: @babel/plugin-transform-regenerator @babel/core @babel/preset-env @babel/register

run babel thru require hook https://babeljs.io/docs/en/babel-register

```
if (
      /** just babel, no webpack section */
      fs.existsSync(path.join(dirPath, ".babelrc")) ||
      fs.existsSync(path.join(dirPath, ".babelrc.js"))
      // // SWYX: TODO - IMPLEMENT
      // || fs.existsSync(path.join(dirPath, "babel.config.js"))
      // || // babel field in package.json
    ) {
      const babelrc = require(path.join(dirPath, ".babelrc.js"));
      // babelrc.extensions = [".js", ".mjs", ".ts"] // doesnt work for some reason
      // babelrc.plugins = ["@babel/plugin-transform-regenerator"]; // maybe needed
      require("@babel/register")(babelrc); // hook
      return require(functionPath);
```

**Comment by ehmicky** [comment]
I think this issue can be generalized to any transpiling/building command. For example, users might run `ts-node`. 

At the moment, `zip-it-and-ship-it` is not executing files. The only thing it's doing with files contents is parsing their AST in order to retrieve the `require()` statements. 

For runtime transpiling (such as `@babel/register` and `ts-node`), this would require modifying users files (injecting JavaScript) before zipping them, which might not be a good idea IMHO.

For compile-time build (such as Babel CLI or TypeScript CLI), this step is currently done separately (before `zip-it-and-ship-it`) by the user or by a tool like Netlify's BuildBot (`build.command`) (please correct me if I'm wrong).

What do you think?

**Comment by ehmicky** [comment]
Based on the comment above, I suggest closing this issue, what do you think?

@erquhart

**Comment by sw-yx** [comment]
:)
