### ISSUE TITLE
Replace our hand wired JS bundling with aws-cdk

### ISSUE THREAD

**Issue by calavera** [netlify/zip-it-and-ship-it#225]
Our JS bundling has many limitations, as @ehmicky discovered over the years, quick examples from issues: #206, #69, #68, #136.

These limitations mean that our customers cannot take advantage of the full potential of AWS Lambda when using via Netlify Functions, because the way that we package those functions is broken in many normal cases.

I'd like to propose replacing the internals of the JS bundling to use the [AWS-CDK](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-lambda-nodejs/lib). By using the officially supported CDK, we get a much better support for all lambda use cases. We also get the advantage of using tooling that is more documented by its maintainers, and a common workflow that can help people migrate from raw AWS usage to Netlify Function with an expected experience shipping their functions.

Changing this also has the advantage of supporting Python bundling, which would be a big plus for customers that want to use Python on Netlify Functions.

Rust and Ruby are not officially supported by AWS, so we'd still to implement #224 and #223 on our own. However, this could be an opportunity to standarize the toolchain for those languages too, and we could offer a very similar experience than Node and Python by following the same conventions that AWS uses in their CDK.

**Comment by ehmicky** [comment]
This is a great idea, our current situation has many problems.
We would want to make sure we are thinking of backward compatibility, since many Netlify Functions are depending on the way bundling is currently performed. For example, which libraries are automatically included or excluded is not always straightforward and depends on specifics of the current algorithm.

**Comment by ehmicky** [comment]
See also https://github.com/netlify/zip-it-and-ship-it/issues/68#issuecomment-724152685

**Comment by erezrokah** [comment]
aws-cdk switched to `esbuild` https://github.com/aws/aws-cdk/pull/11289

**Comment by ehmicky** [comment]
To help with possibly migrating to AWS-CDK / `esbuild`, I compiled a list of potential gotchas we should look for to provide with a smooth transition for users. We would need to make sure that:
  - [ ] The bundle size does not increase too much. Otherwise, some sites Functions would hit the max size limit in AWS Lambda. Also, this would take more space for us to store (@netlify/sre).
  - [ ] [Temporary files](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/index.js#L32) are still excluded. Also [lock files, source maps](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/published.js#L24), etc.
  - [ ] [`aws-cdk` itself and TypeScript types are still](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/index.js#L191) excluded.
  - [ ] [Every file in a Functions directory](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/tree_files.js#L7) is still included, unless we manage to exclude some in a backward compatible way.
  - [ ] Next-on-netlify and our Next.js plugin are still [properly tree shaked](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/index.js#L95) (@lindsaylevine @cassidoo).
  - [ ] Bundling still works with Prisma (see [this](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/side_files.js#L15) and [that](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/nested.js#L21)) and with [`critters`](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/nested.js#L75).
  - [ ] Node.js 8 [is still supported](https://github.com/netlify/build/issues/939) (until we finally drop support for it)
  - [ ] This works with sites [without a `package.json`](https://github.com/netlify/zip-it-and-ship-it/blob/c17440c2a14c35521cb123c51516d4d86645204e/src/node_dependencies/package_json.js#L7)

Finally, this is user-facing and there probably should be some product design around bundling configuration: do we allow configuring it? Do we use `esbuild` standard configuration file, or do we provide with our own configuration abstraction in-between?

**Comment by erezrokah** [comment]
Also nice to have:

- [ ] Works out of the box with `firebase` and/or `firebase-admin` (possibly other common libs)

**Comment by ehmicky** [comment]
We can also check [Datadog](https://app.datadoghq.com/dashboard/a9h-wan-dta/buildbot?from_ts=1611841047540&fullscreen_section=overview&fullscreen_widget=1069011713734887&live=true&tile_size=m&to_ts=1611927447540&fullscreen_start_ts=1611846203768&fullscreen_end_ts=1611932603768&fullscreen_paused=false) to see how much this speeds up Functions bundling. This would be a great side effect of this (`esbuild` seems to be much faster).

**Comment by eduardoboucas** [comment]
It's now possible to bundle using esbuild! 🎉
