### ISSUE TITLE
Chore: drop Node.js 8 support

### ISSUE THREAD

**Issue by erezrokah** [netlify/zip-it-and-ship-it#294]
Following up with https://github.com/netlify/cli/issues/1568, we should be good now with dropping Node.js 8 support for the `zip-it-and-ship-it`.

**Comment by ehmicky** [comment]
`@netlify/build` uses `@netlify/zip-it-and-ship-it` in production, so this depends on Node 8 support being dropped from `@netlify/build` first (https://github.com/netlify/team-dev/issues/2).

**Comment by erezrokah** [comment]
Thanks for clarifying, I was only thinking about the core plugin use case.

**Comment by erezrokah** [comment]
Linking [this branch](https://github.com/netlify/zip-it-and-ship-it/tree/feat/drop_node_8) for future reference.

**Comment by ehmicky** [comment]
Node 8 had to be dropped in all methods except `list()` and `listAll()` due to `archiver@v4` not supporting Node 16, but `archiver@v5` supporting Node 16 but not Node 8. See https://github.com/netlify/zip-it-and-ship-it/issues/463

**Comment by ehmicky** [comment]
After doing some research, I would suggest that we directly drop Node 8 support in the whole package (including `list()` and `listAll()`) due to the very minimal risk:
  - No npm package seems to require `@netlify/functions-utils` directly
  - The only plugin using `@netlify/functions-utils` is [`neltify-plugin-inline-functions-env`](https://github.com/bencao/netlify-plugin-inline-functions-env/blob/c3866ce029bb93b35ed3000e554be8c85be8892a/index.js#L36). From Humio logs, it appears that no site using this plugin is both installing it in `package.json` and using Node 8
  - The risk of local plugins using `utils.functions` while using Node 8 seems minimal, although there is no available data about this

What are your thoughts?

Note: this would also moving the `require('archiver')` statement back to the top-level scope.

**Comment by eduardoboucas** [comment]
This sounds great, thanks for following up on this @ehmicky!

I've assigned this to myself, I'm happy to take it from here.

**Comment by ehmicky** [comment]
This might be required to fix https://github.com/netlify/zip-it-and-ship-it/issues/477
See https://github.com/dependents/node-precinct/blob/802dba3abe6a3c17562d5d5fd1f84151e7fb9ec7/package.json#L32
