### ISSUE TITLE
This does not work with dynamic or conditional module imports

### ISSUE THREAD

**Issue by ehmicky** [netlify/zip-it-and-ship-it#68]
Some Node modules do this:

```js
try {
  require('moduleName')
} catch (error) {}
```

Or this:

```js
if (condition) {
  require('moduleName')
}
```

[Or this](https://github.com/ardatan/graphql-toolkit/blob/e6acc231db1b6ac1a11aec33a1ddf55f0f45337e/packages/loaders/code-file/src/extract-document-string-from-code-file.ts#L52):

```js
eval(`require('moduleName')`)
```

Or this:

```js
require(getModuleName())
```

A common example is `node-fetch` which [conditionally require `encoding`](https://github.com/bitinn/node-fetch/blob/8c197f8982a238b3c345c64b17bfa92e16b4f7c4/src/body.js#L14). `encoding` is only used with the `textConverted` method, which [throws if it's missing](https://github.com/bitinn/node-fetch/blob/8c197f8982a238b3c345c64b17bfa92e16b4f7c4/src/body.js#L285).

Another example is `@nestjs/graphql` which [uses `apollo-server-core`](https://github.com/nestjs/graphql/blob/f807e29bce2cdb6254b06b4be5e531e5b7b7e26c/lib/graphql-definitions.factory.ts#L2) but does not declare it in its [production `dependencies`](https://github.com/nestjs/graphql/blob/f807e29bce2cdb6254b06b4be5e531e5b7b7e26c/package.json#L41).

The reason why some modules might want to do this and not use `optionalDependencies` is to allow users to opt-in to installing specific modules. 

However this creates the following two issues with `zip-it-and-ship-it`. When the conditional `require()` is performed: 
  1. Directly from a function file, `zip-it-and-ship-it` always bundles the dependency. Users should have a way to exclude such modules in the archive if they want to.
  2. From a node module, `zip-it-and-ship-it` never bundles the dependency. This is because we find nested dependencies by only checking the `package.json` `dependencies`, `peerDependencies` and `optionalDependencies` keys (as opposed to look for `require()` statements). Users should have a way to include such modules in the archive if they want to. 

The current workaround are (for the points above):
  1. User should `npm install` the dependency
  2. User should `npm install` the dependency and add a noop `require()` call in its function file code.

However this feels hacky, so we should think of a better solution.

**Comment by DavidWells** [comment]
Almost all function bundling solutions have the concept of `includes` & `excludes` options

This covered the missing pieces when trying to parse the AST or use recursive `package.json` files to includes the exact files needed for deployment.

[example](https://github.com/techmagic-team/sls-monitoring/blob/078ae87b38918a2deba2d1df138b643718f4c3dd/src/api/accounts/serverless.yml#L4-L8)

We most likely need a higher level option for users to explicitly include/exclude files from the packaging step during the build

**Comment by ehmicky** [comment]
An additional use case: some libraries create their source files at runtime or during `postinstall`. For example, Prisma generates its client and outputs it under `node_modules/.prisma`. 

This is a little different from the cases above because we crawl Node modules differently. Instead of using `require()` statements, we use the `files` field from `package.json`. This does not work with dynamically generated source files.

**Comment by Rich-Harris** [comment]
Bumping this issue, as it was the first problem I encountered when trying to use Netlify functions. It seems to me that the correct behaviour here would be to ignore modules that can't be resolved — if they fail at runtime, so be it (though as @ehmicky describes this is often used to detect the presence of optional dependencies, meaning 'failure' is generally intentional in these cases).

Short of that, a warning could be printed to help track down the cause of those runtime errors.

With the current behaviour, you have to jump through some very complex hoops to get widely-used packages like `node-fetch` working with functions, even once you've diagnosed the problem. The end result is that functions are essentially unusable for apps that depend on those packages.

**Comment by witcradg** [comment]
Possibly related to issue #205.

**Comment by kentcdodds** [comment]
[Remix](https://remix.run) will need this (or they'll have to do some extra fanciness during the build). I've put together a simple example repo (without remix) that works locally, but not in production:

- https://github.com/kentcdodds/netlify-dynamic-require
- https://condescending-bassi-78ec13.netlify.app/.netlify/functions/index

Here's what it looks like locally:

![image](https://user-images.githubusercontent.com/1500684/97238144-4c7de700-17ae-11eb-95fd-3231e65f9343.png)

**Comment by ehmicky** [comment]
Hi @kentcdodds,

What's not currently supported are `require()` statements that are not top-level (e.g. inside an `if` or a function) or whose argument is not a string literal. Your example repository should work. I have [reproduced it](https://github.com/ehmicky/cv-website/commit/3ad7f2260c46d21c75c39da1c13a06b1fa90d2c8) and the endpoint [works in production](https://mickael-hebert.com/.netlify/functions/time).

Cloning your repository, your problem might be different ([see build logs](https://app.netlify.com/sites/wonderful-mayer-f83167/deploys/5f9801d086bec66feb0fbc7e)). In order for Netlify Functions to work properly, you currently need a build command, otherwise those functions won't be bundled by `zip-it-and-ship-it` (except locally, as you noticed). We are actually currently fixing that bug. In the meantime, using `#` as your build command should fix this problem.

**Comment by kentcdodds** [comment]
Ah, thanks for clearing that up @ehmicky. So I've updated the project to make it an actual dynamic require and added a build command. Once dynamic requires are supported, then I'll get it updated to serve as an example :) Thanks!

**Comment by ehmicky** [comment]
Do you have some additional insights into the requirements of Remix for this feature? 
I am especially wondering about which type of dynamic `require()` is needed? Among: 
  - conditional `require()`: inside an `if` block
  - `require()` inside a `try`/`catch` block
  - lazy `require()`: called inside a function
  - dynamic argument: `require()` which argument is not a string constant

**Comment by kentcdodds** [comment]
I'm not sure actually. All I know is the files need to be in a specific structure and require-able by that structure at runtime

**Comment by ryanflorence** [comment]
@ehmicky We just need an `include` option to specify which files to also deploy to the function so that dynamic requires work. It's not about "conditional requires", it's non-static requires.

For example, other serverless functions like vercel have an option to indicate other files that are needed, but you won't find by static analysis of requires:

```json
{
  "includeFiles": ["remix.config.js", "build/**/*.js"]
}
```

**Comment by ryanflorence** [comment]
Little more background, when the remix request handler gets a request, it matches against the routes and then dynamically requires the "route loaders" (functions that fetch data server side for the view). We're considering changing our build step to turn all of that into static requires in the entry of the function, but at the moment it's dynamic.

An `include` option would let us use netlify right away.

**Comment by reimertz** [comment]
> @ehmicky We just need an `include` option to specify which files to also deploy to the function so that dynamic requires work. It's not about "conditional requires", it's non-static requires.
> 
> For example, other serverless functions like vercel have an option to indicate other files that are needed that you won't find by static analysis of requires:
> 
> ```json
> {
>   "includeFiles": ["remix.config.js", "build/**/*.js"]
> }
> ```

Agree with this! 

Seems like such a low hanging fruit enabling the ability to bundle things such as content editable with Netlify CMS.

**Comment by ehmicky** [comment]
Whichever solution is chosen would need to allow including/excluding files both: 
  - In the Netlify Function itself: for example, if a `functions/example.js` is doing a dynamic require
  - In the Netlify Function's dependencies: for example, if a Function is using a library like Remix which would do a dynamic require

This raises the following questions:
  - Where does the include/exclude list go: in `netlify.toml`, in plugin inputs, in the site `package.json`, in the Function file (e.g. as code comments), in a separate configuration file?
  - When using a library with dynamic requires, who should specify this list: the dependency's maintainers, the dependency's users, or both?

@calavera mentioned #225 as a possible solution for this, providing it does solve those two questions.

**Comment by kentcdodds** [comment]
I vote the include/exclude should go in `netlify.toml`. However I also vote that both a dep's maintainer as well as the dep's users should be able to specify include/exclude. For that to work, it probably makes sense to allow this to be configured in the `package.json` (as well?)

**Comment by ehmicky** [comment]
Please note that when it comes to Functions' dependencies, `zip-it-and-ship-it` automatically bundles any files that's been published to npm (with some minor exceptions like lock files or source maps) (see [logic here](https://github.com/netlify/zip-it-and-ship-it/blob/a2d6da7ae108465cc5e116afa88420e0bac0970f/src/dependencies.js#L189)). So, as a library maintainer, Netlify Functions will bundle the file providing it is published to npm. This has some shortcomings though: too many files are included (no tree shaking) and it does not work with files generated at runtime or at `postinstall`. I am wondering whether this might be sufficient for Remix though @kentcdodds?

The situation is different with Netlify Functions files themselves. For those, we parse the JavaScript code, look for top-level `require()` statements and only include those dependencies (tree shaking).

**Comment by kentcdodds** [comment]
I think that's sufficient for remix. AFAIK, remix only dynamically requires user code.

**Comment by Offirmo** [comment]
Regarding issue 1), couldn't we solve it by not requiring the module. If it's present in node_modules, add it. If it's not available, don't fail.

**Comment by ryanflorence** [comment]
@ehmicky 

> **Where does the include/exclude list go: in netlify.toml**

Yes. Seems like the only place to do it, from your docs:

> The netlify.toml file is your configuration file on how Netlify will build and deploy your site

> **When using a library with dynamic requires, who should specify this list: the dependency's maintainers, the dependency's users, or both?**

Only the app that's being deployed should have to worry about configuring this.

In the case of Remix, as a dependency, we don't dynamically require any of *our own* modules, otherwise they wouldn't be dynamic! The requires are dynamic because we don't know the names of the files: they're supplied by the app. Additionally, apps get to configure where their "data loaders" live, so we wouldn't even be able to specify this information ourselves anyway. They're app modules.

Another case is Prism.js. It does dynamic requires for plugins and themes. If I'm deploying a markdown blog with prism, I would definitely **not** want prism to be defining every possible file that could be required and then netlify deploying a bunch of code I don't use (and if those modules have side-effects, they'd likely break something).

I think the only thing you need is an `include` option with an array of glob patterns:


```toml
[build]
  base = "project/"
  publish = "build-output/"
  command = "echo 'default context'"
  functions = "src/"
  include = [ "src/app/remix.config.js", "src/app/build/**/*", "src/app/node_modules/prisms/plugins/whatever.js" ]
```

**Comment by ryanflorence** [comment]
Oh, just noticed this recommended directory structure at https://docs.netlify.com/functions/build-with-javascript/#unbundled-javascript-function-deploys

```
├─ my-base-directory
│  ├─ package.json
│  └─ node_modules
└─ my-serverless-functions
   └─ hello.js
   └─ send-pdf-background.js
```

If that's the recommend structure, then I think the `netlify.toml` makes sense. Then the "build bot" mentioned can do its normal thing, and then look at the "include" key in `netlify.toml` then glob that extra stuff in, and it's done!

I don't think it needs to be much more complicated than that 😁

And to reiterate, I really don't think you should want third party dependencies able to define behavior of a Netlify customer's deployment config 😬 Too many dragons there with module side-effects and unnecessarily inflating the size of the zip (and therefore cold starts, etc.). What will end up happening is you'll need an "exclude" and then it's this battle between the app and the dependencies on what gets deployed.

**Comment by ryanflorence** [comment]
Wait a sec, doesn't this test show that it keeps the files around? https://github.com/netlify/zip-it-and-ship-it/blob/master/src/main.test.js#L176-L179

**Comment by ryanflorence** [comment]
Poked around the code a bit and have a couple more ideas:

Dynamic requires work, but only if the files are in the root of the function folder. There's even a test for it: https://github.com/netlify/zip-it-and-ship-it/tree/8b69c8db48ef639b86d444e88f5a905c67e746ba/tests/fixtures/keep-dir-files/function

It's unclear to me why files in the root of the function are included, but files in sub directories are not. The only way files in sub directories get included is if they are in the main function's module dependency graph.

The code here is what creates this limitation and inconsistency: https://github.com/netlify/zip-it-and-ship-it/blob/8b69c8db48ef639b86d444e88f5a905c67e746ba/src/info.js#L27

My thoughts are:

1. Make that a recursive readdir instead of flat. That way there's not this unclear reason why root level modules get to survive the zip, but sub directory modules don't.

2. Don't try to optimize by tracing the require graph or reading directories, just zip up the function folder and send it to AWS. Server code isn't typically compiled, so if the files are in the function's folder, seems like the assumption is they are needed for the function to run, whether they are in the require graph or not (or are root modules or not).

**Comment by ryanflorence** [comment]
After poking around the code a bit, I think https://github.com/netlify/zip-it-and-ship-it/issues/225 is probably the right approach here :)

**Comment by eduardoboucas** [comment]
I believe all the problems described here were addressed:

- It's now possible to include any files in the bundle using the `included_files` configuration property (https://www.netlify.com/blog/2021/08/12/how-to-include-files-in-netlify-serverless-functions/)
- We have better support for imports using dynamic expressions when using esbuild (https://www.netlify.com/blog/2021/04/02/modern-faster-netlify-functions/)

If there's any part of this thread that hasn't been addressed yet, please add a comment and I'll reopen the issue.

Thanks!
