### ISSUE TITLE
Native modules support

### ISSUE THREAD

**Issue by ehmicky** [netlify/zip-it-and-ship-it#69]
Native modules must be built and run on the same OS. Our build system runs on Linux and so do our AWS Lambda functions. However there are several posts that describe a bigger setup to get any native modules working on AWS Lambda. Do we support native modules on Netlify Functions?

Also they must also be built and run on the same Node.js version. Otherwise they show some error message when run. Our build system uses the `NODE_VERSION` environment variable or `.nvmrc` file, with a default of Node `10.*.*`. However our AWS Lambda functions use the `AWS_LAMBDA_JS_RUNTIME` environment variable, with a default of Node `8.10.0`. Note that Node.js version is not relevant when using [N-API](https://nodejs.org/api/n-api.html) but not all native modules are using this yet.

**Comment by ehmicky** [comment]
Note: this issue is being reported in #79 as well.

**Comment by eduardoboucas** [comment]
@ehmicky I don't think there's anything more that zip-it-and-ship-it specifically can do about native module support right now. Since https://github.com/netlify/zip-it-and-ship-it/pull/433, it returns a list of any native modules it finds, so that CLI can warn users when deploying locally.

Do you think we can close this one, or do you have anything else in mind?

**Comment by ehmicky** [comment]
:+1:
