### ISSUE TITLE
Add support for optional peer dependencies

### ISSUE THREAD

**Issue by kripod** [netlify/zip-it-and-ship-it#74]
While [trying to deploy](https://community.netlify.com/t/cannot-upload-build-function-to-aws-lambda/5261) a GraphQL server utilizing Prisma Framework, I observed that the generated bundle is overly large (~70 MB), due to the fact that `prisma2` gets bundled as being the peer dependency of `@prisma/photon`. In order to avoid this behavior, I'm [making `prisma2` an optional peer dependency](https://github.com/prisma/photonjs/pull/313) of `@prisma/photon` by using the `peerDependenciesMeta` property in `package.json` [introduced by Yarn](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md).

This project should avoid bundling optional dependencies by default, with exclusions specifiable through additional configuration.

**Comment by ehmicky** [comment]
Hi @kripod, thanks a lot for reaching out!

Some background: the reason we include `peerDependencies` is because this is quite common for modules to either directly include one of their `peerDependencies` or to trigger its binary.

Now we also include `optionalDependencies` because there's no way to determine whether those are meant to be used or not, so we fall back on the safe side.

Optional peer dependencies are a combination of the two above, i.e. they should be included as well, not excluded.

The real problem here is that it's hard to determine whether a `peerDependencies` is directly used or not, i.e. should be bundled. Since missing dependencies would make a Netlify Function crash, we fall back on the safe side here as well. However false positives lead to bigger Functions archives, which can hit the maximum size limit with AWS Lambda (as you [reported](https://community.netlify.com/t/cannot-upload-build-function-to-aws-lambda/5261/8)). This is your case, where it seems like `prisma2` is only needed during `postinstall`, i.e. it should not be bundled.

I think there is a way to solve your issue though, that I will describe in the separate issue #73. :)

**Comment by kripod** [comment]
Thank you for pointing out all the concerns regarding this idea. I'm closing this, superseded by other issues mentioned in #73.
