### ISSUE TITLE
Inline environment variables to be seen by AWS Lambda

### ISSUE THREAD

**Issue by kripod** [netlify/zip-it-and-ship-it#76]
In order to make environment variables available in environments outside Netlify, they should be inlined with [babel-plugin-transform-inline-environment-variables](https://babeljs.io/docs/en/babel-plugin-transform-inline-environment-variables), as suggested [here](https://stackoverflow.com/questions/43786682/aws-lambda-environment-variables-not-set-process-env-undefined-in-node).

**Comment by ehmicky** [comment]
Hi @kripod,

Thanks a lot for the suggestion. 
I don't think every user is expecting environment variables set at build time (when function is bundled on your local machine or in Netlify CI) to also be set at runtime (when function is called in AWS Lambda). You would also need to consider excluding environment variables that contains secrets.

When it comes to setting environment variables you can set those [in multiple ways](https://docs.netlify.com/configure-builds/environment-variables/). 

Also we are supporting other languages than Node.js (e.g. Go) where Babel plugins would not work.

That being said, Netlify Functions are designed to allow you to specify `build` steps before bundling them, so you should be able to run Babel (and `babel-plugin-transform-inline-environment-variables`) in the `build` step of your project.

**Comment by ehmicky** [comment]
Hi @kripod,

Thanks a lot for the suggestion. 

Some environment variables can be inlined since they are meant to use the build time value (when function is bundled on your local machine or in Netlify CI) such as `NODE_ENV`. But other environment variables are meant to use the runtime value (when function is called in AWS Lambda). 

That being said, Netlify Functions are designed to allow you to specify `build` steps before bundling them, so you should be able to run Babel (and `babel-plugin-transform-inline-environment-variables`) in the `build` step of your project. This is the recommended way to perform transformation on your function files (such as environment variables inlining) before bundling them.

**Comment by zoexx** [comment]
hi there, since move to `esbuild` in zisi step, it become not so good to maintain a webpack or babel manually (just for inline the envs).
Could it be able to inline the envs by default ?
Do you have any suggestion to reslove the envs with current `esbuild`?  @ehmicky

**Comment by eduardoboucas** [comment]
Hey @zoexx. As I mentioned in https://github.com/netlify/zip-it-and-ship-it/issues/584#issuecomment-887333828, we'll be able to solve this by tapping into esbuild's `define` parameter via a configuration property. I'll keep #584 updated with progress on this.
