### ISSUE TITLE
Remove src/utils/shell.ts?

### ISSUE THREAD

**Issue by XhmikosR** [netlify/zip-it-and-ship-it#942]
Just going through the source code, I noticed this file is just exporting execa.

Wouldn't it be simpler to remove it and call execa directly in the two places you are using it?

**Comment by eduardoboucas** [comment]
We're using it mostly in order to stub execa in tests. See https://github.com/netlify/zip-it-and-ship-it/blob/070393471c9147974f1c11e2b17dfb3fd5a4c6f6/tests/main.js#L23-L28.

It's not an ideal solution, but it feels like a harmless abstraction that does the job. I'm happy to look into alternative approaches, though.

**Comment by XhmikosR** [comment]
I figure out it's only for tests too, but I couldn't make tests works right. I'd definitely remove it because it's unnecessary for production, but I don't have a solution to offer.
